### ISSUE TITLE
Upload tutor-contrib-harmony to pypi

### ISSUE THREAD

**Issue by Ian2012** [openedx/openedx-k8s-harmony#114]
To facilitate adoption we should add tutor-contrib-harmony to the PyPI registry. This would require adding a second release workflow triggered on created releases which follow the pattern vN.N.N and package the repository correctly.

Another approach would be to split this repo into his two components.

**Comment by bradenmacdonald** [comment]
Do you mean the tutor plugin? Because the main harmony project is not a python package.

**Comment by bradenmacdonald** [comment]
Sounds good! There are already workflows for this on other openedx repos, so we can probably just copy it over.

**Comment by Ian2012** [comment]
Closed by #116
