### ISSUE TITLE
Register the group as a formal working group - Discovery

### ISSUE THREAD

**Issue by antoviaque** [openedx/openedx-k8s-harmony#12]
So far the working group has been mostly informal, but as we are beginning to produce more concrete work, it could make sense to formalize the group a bit more. As a subgroup of the new devops working group?

Scope/title of the subgroup TBD - "Big/multi instances"?

See with tCRIL engineering what would be required exactly, and what would be the artifacts to produce for the registration.

**Comment by antoviaque** [comment]
Asked a question about this in https://github.com/openedx/tcril-engineering/issues/617 which was opened as part of https://github.com/openedx/tcril-engineering/issues/617

**Comment by antoviaque** [comment]
Cf https://github.com/openedx/tcril-engineering/issues/617

>  For more formalizing, I'd talk to the chair of the Devops group and then follow https://openedx.atlassian.net/wiki/spaces/COMM/pages/3621519401/How+to+Make+a+New+Working+Group to start up the working group.

**Comment by antoviaque** [comment]
@regisb I was hoping to discuss this further during the meeting yesterday, but I wasn't able to attend. I can take care of the steps from https://openedx.atlassian.net/wiki/spaces/COMM/pages/3621519401/How+to+Make+a+New+Working+Group but how do you see this, are there specific points that would be worth discussing before I do that?

**Comment by regisb** [comment]
Thanks for the ping @antoviaque! I had indeed missed the notification.

> are there specific points that would be worth discussing before I do that?

From my perspective, I'd like to make sure that the links to the working group are correct on this page: https://github.com/openedx/wg-devops/
In particular, I think it's important that external contributors have a clear set of "good first issues" that they can help with: https://github.com/openedx/wg-devops/#how-to-get-started-fixing-issues
Once you have created the relevant forum category and Slack channel, can you please open a PR to the wg-devops repo to amend the links?

**Comment by regisb** [comment]
> Imho it would be simpler to keep the discussions there in one place, until/unless we take too much space?

Yes, I agree. From your previous comment, I incorrectly assumed that you wanted to create a dedicated discourse category and Slack channel. I also think it would be preferable to have conversations in #wg-devops.

**Comment by antoviaque** [comment]
FYI, I have started drafting a page to describe the group at https://openedx.atlassian.net/wiki/spaces/COMM/pages/3655008783/Large+Instances+-+DevOps+Sub-Working+Group - comments/edits welcomed.

Next steps:
* Create the "good first issues" category for github issues
* Review the charter with the group in the next meetup
* Nominate a chair for the group
* Add the group description to: 
** DevOps WG https://github.com/openedx/wg-devops/
** List of working groups https://openedx.atlassian.net/wiki/spaces/COMM/pages/46793351/Open+edX+Working+Groups
* Write an announcement in the forum

**Comment by antoviaque** [comment]
@regisb Btw I don't see the label "good-first-issue" in the current repo: https://github.com/openedx/tutor-contrib-multi/labels

Though I see it on the devops WG repo: https://github.com/openedx/wg-devops/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue

Do you think it would be worth making this label global to the openedx org? This way we would be able to reuse it everywhere. I assume this would require a ticket to tcril-engineering?

**Comment by antoviaque** [comment]
This has been mentioned during yesterday's meeting:

> * Review the charter with the group in the next meetup

Group members will comment directly on the wiki page at https://openedx.atlassian.net/wiki/spaces/COMM/pages/3655008783/Large+Instances+-+DevOps+Sub-Working+Group

> * Nominate a chair for the group

We have discussed and agreed that Braden and Felipe are good leads for the group and project, I've also added them in the chair section since there is very little difference currently.

Now I have done:

> * Add the group description to:
>   *  DevOps WG https://github.com/openedx/wg-devops/

PR created: https://github.com/openedx/wg-devops/pull/2

> * Add the group description to:
>  * List of working groups https://openedx.atlassian.net/wiki/spaces/COMM/pages/46793351/Open+edX+Working+Groups

Done.

The only steps remaining are:

* Create the "good first issues" category for github issues => depends on https://github.com/openedx/terraform-github/issues/51
* Merge https://github.com/openedx/wg-devops/pull/2
* Write an announcement in the forum

**Comment by antoviaque** [comment]
Update on the remaining steps:

> Create the "good first issues" category for github issues => depends on
https://github.com/openedx/terraform-github/issues/51

This is still in progress/discussion in the linked ticket.

> Merge https://github.com/openedx/wg-devops/pull/2

Done!

> Write an announcement in the forum

TBD once the rest is done.

**Comment by antoviaque** [comment]
> Create the "good first issues" category for github issues

This is unblocked, and I have assigned the label "good first issue :tada:" to a couple of issues. They now appear on https://github.com/orgs/openedx/projects/42/views/3

And as a result, I was able to post the forum announcement, which was the last step of the working group creation process. This task is thus now done:

https://discuss.openedx.org/t/working-group-creation-large-instances-multisites/9488
