### ISSUE TITLE
Deploy shared OpenSearch onto the cluster

### ISSUE THREAD

**Issue by keithgg** [openedx/openedx-k8s-harmony#21]
There is already an implementation for running [Shared Elasticsearch ](https://github.com/openedx/openedx-k8s-harmony/issues/4) on the cluster. Implement a similar solution for OpenSearch. This is not to replace the ES configuration, but rather live alongside it.

Notes for implementation:

- Most config values that contain "elasticsearch" will now be "opensearch"
- The certificates generated will likely work with OpenSearch except for some naming issues.
- Users and roles are created using the ElasticSearch API. It shouldn't require any changes except for updating URL.

**Comment by cmltaWt0** [comment]
Let me try move the issue forward.

**Comment by felipemontoya** [comment]
This work is being tracked in the PR: https://github.com/openedx/openedx-k8s-harmony/pull/31

**Comment by cmltaWt0** [comment]
PR is ready for review.

**Comment by cmltaWt0** [comment]
Closing the issue. PR is merged.
