### ISSUE TITLE
Once the Harmony Tutor plugin is stable, add it to the "contrib" plugin index

### ISSUE THREAD

**Issue by regisb** [openedx/openedx-k8s-harmony#22]
Tutor [plugin indexes](https://docs.tutor.overhang.io/reference/indexes.html) are a thing now, and the easiest way for users to manage plugins is with `tutor plugins install/upgrade/uninstall pluginname`. Once the openedx-k8s-harmony is stable, would you consider adding it to the ["contrib" index](https://github.com/overhangio/tpi#contrib)? I think it would make sense.

**Comment by bradenmacdonald** [comment]
Suggestion: wait until we have at least one provider using this in production, then publish the plugin on the index.

**Comment by gabor-boros** [comment]
As OpenCraft is now using the plugin, I think we can add it to TPI.
cc: @bradenmacdonald

**Comment by bradenmacdonald** [comment]
@gabor-boros  Sounds good, let's do that.
