### ISSUE TITLE
Enable verified SSL support for the Elasticsearch/Opensearch cluster

### ISSUE THREAD

**Issue by keithgg** [openedx/openedx-k8s-harmony#23]
Shared Elasticsearch was implemented in #13. While SSL is implemented it could not be completed due to https://github.com/overhangio/tutor/issues/791. That PR has now been merged, so this can be tackled.

- Add a Kubernetes `Secret` to store the CA certificate generated by the helm chart.
- Mount this secret inside each container that will require it under the directory `/etc/ssl/certs/elasticsearch-ca.pem`.
- For the forum, check out the PR https://github.com/openedx/cs_comments_service/pull/404

**Comment by felipemontoya** [comment]
@MoisesGSalas do you know if it possible to use the certbot process to create this certs instead of relying on self-signed certs?

**Comment by gabor-boros** [comment]
I just figured out that Tutor 16 includes a newer version of `dockerize` that now supports `-cacert` flag. Using that flag, we could let dockerize know we want to use the custom cert we created, however that requires modifications in the tutor-forum [source code](https://github.com/overhangio/tutor-forum/blob/v16.0.0/tutorforum/templates/forum/build/forum/bin/docker-entrypoint.sh#L17) to optionally pass the `-cacert` flag if the CA check would fail.

One option for that could be:

```bash
# ...

WAIT_SEARCH_SERVER="-wait $SEARCH_SERVER"
if [[ -n $(curl --verbose --silent "${SEARCH_SERVER}" 2>&1 | grep "TLS alert, unknown CA") ]]; then
    CA_CERT_PATH="...somehow get the path..."
    WAIT_SEARCH_SERVER="${WAIT_SEARCH_SERVER} -cacert ${CA_CERT_PATH}"
fi

# ...

dockerize $WAIT_MONGODB $WAIT_SEARCH_SERVER -wait-retry-interval 5s -timeout 600s

**Comment by bradenmacdonald** [comment]
> Doing so will let us issue the certificate and configure it for Elasticsearch. The server will pick up the certificate with ease, though the question raises: How to communicate with the server? The main concern is that we have to a) reach out to the internet to get back to the server

Can't you use DNS within the cluster to point that domain name to a cluster-local endpoint, so we don't have to reach out over the internet? i.e. LetsEncrypt sees `es1.mycluster.example.com` as the ingress IP, but within the cluster, `es1.mycluster.example.com` resolves to the ES service and doesn't get resolved via the internet.

I'm also fine with using self-signed certs or some simpler option though; we have other priorities at the moment.

**Comment by gabor-boros** [comment]
@bradenmacdonald I was trying to dig into this. In the Kubernetes cluster, the DNS resolution of *.svc.local addresses are handled automatically by CoreDNS and .svc.local addresses are added/removed as needed. I did not find a way though to extend it with custom records. Also, I feel that would be a bit of hacking to "fake" the DNS record we want to get resolved (`es1.mycluster.example.com`).

I'm fine with self-signed certs as well, though my question still stands: Do we want to really make the effort to let the pods trusting the cluster-local CA? The whole traffic is happening within the cluster.
