### ISSUE TITLE
Hosting of the Harmony Chart

### ISSUE THREAD

**Issue by jfavellar90** [openedx/openedx-k8s-harmony#33]
One of the points open in our list of [TODOs](https://github.com/openedx/openedx-k8s-harmony/issues/26#issuecomment-1485856547) to make this project usable in pŕoduction is the hosting of the Harmony chart. Currently, to install this chart correctly, we need to clone the whole **openedx-k8s-harmony** repository and use Helm to install it from the source code. Additionally, we need to push the artifacts of the dependency charts to prevent running extra commands when installing the main chart. This is not ideal from an operator's perspective.

We should stick to the standard and host the chart in a [Helm repository](https://helm.sh/docs/topics/chart_repository/#hosting-chart-repositories) to make its installation more intuitive:

```
helm repo add openedx-harmony <repo_url>
helm install <release_name> openedx-harmony/harmony-chart --values values.yaml
```
There's a tool called [chart-releaser](https://github.com/helm/chart-releaser) that helps to add Helm chart artifacts to GitHub Releases and host such releases in GitHub pages. To automate the process, the [chart-releaser-action](https://github.com/helm/chart-releaser-action) can be included in the repo workflow to create new releases of the chart and update properly the GitHub Pages hosting. The prerequisites to use the action are included [here](https://github.com/helm/chart-releaser-action#pre-requisites).

This releaser is used by most of the well-known Helm charts (ingress-nginx, prometheus-charts, among others) to handle the releases and the hosting. However, the discussion is open to bring other options to the table.

**Comment by jfavellar90** [comment]
Guys, I stepped up and created a [PR](https://github.com/openedx/openedx-k8s-harmony/pull/36) to implement the release and hosting mechanisms of the harmony chart using chart-releaser. Feel free to check it out and provide feedback :)

**Comment by felipemontoya** [comment]
Updated PR: https://github.com/openedx/openedx-k8s-harmony/pull/40

**Comment by felipemontoya** [comment]
This was fixed by PR40 so I'm closing now
