### ISSUE TITLE
Variable Error

### ISSUE THREAD

**Issue by jo316it** [openedx/openedx-k8s-harmony#44]
Well, when I get in to the part where you have to put variables above:

```
export INSTANCE_ID=openedx-01
export TUTOR_ROOT=~/deployments/tutor-k8s/$INSTANCE_ID
tutor plugins enable k8s_harmony
tutor config save -i --set K8S_NAMESPACE=$INSTANCE_ID
```
This error occours:

`Error: Missing configuration value: 'K8S_NAMESPACE' is undefined"`
But if ai tip echo “$K8S_NAMESPACE” this variable exists.

Someone just saw this error?

**Comment by bradenmacdonald** [comment]
> But if ai tip echo “$K8S_NAMESPACE” this variable exists.

It sounds like you might have it set as an environment variable? But it's a tutor config variable.

I'm not sure why you're getting that error as [the setting definitely exists](https://github.com/search?q=repo%3Aoverhangio%2Ftutor+K8S_NAMESPACE&type=code). At the very least you can find the instance's `config.yml` file and change the setting manually.

Or perhaps you didn't set the `$INSTANCE_ID` environment variable correctly? In that case, running `tutor config save -i --set K8S_NAMESPACE=$INSTANCE_ID` would set the tutor `K8S_NAMESPACE` variable to an empty string, which could cause the error you are seeing. Type `echo $INSTANCE_ID` and make sure something is printed out.

**Comment by jo316it** [comment]
Hi Branden, thank you to asnwer.
Grace to you I got it. I put the manualy the K8S_NAMESPACE on config.yml and now it's work fine!
