### ISSUE TITLE
Need a new name for this project

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/openedx-k8s-harmony#5]
This isn't really directly related to tutor - it's about best practices for deploying **Open edX** onto Kubernetes, using Tutor.

So let's get a better name for it.

**Comment by bradenmacdonald** [comment]
ChatGPT came up with the following ideas:

> here are some potential more creative or abstract names for a project that helps run multiple instances of Open edX on a Kubernetes cluster:

* Open edX Conductor
* Open edX Harmony
* Open edX Symphony
* Open edX Ensemble
* Open edX Oasis
* Open edX Cloudburst
* Open edX Matrix
* Open edX Vortex
* Open edX Supernova
* Open edX Metamorphosis
* Open edX Mosaic
* Open edX Catalyst
* Open edX Eclipse
* Open edX Mirage
* Open edX Frontier
* Open edX Nexus
* Open edX Horizon

**Comment by antoviaque** [comment]
@bradenmacdonald Since you haven't had many replies here, to move forward with this, maybe put a poll in a forum thread with your favorites from the list? https://rankit.vote/ would allow to use a Condorcet rank voting approach

Personally, I like:
* Catalyst
* Conductor
* Harmony
* Vortex

Some, like Symphony or Horizon, are already names of popular open source projects, so we should probably avoid them. :)

**Comment by bradenmacdonald** [comment]
@antoviaque Good idea.
I posted a poll and some new options at https://discuss.openedx.org/t/deploying-open-edx-on-kubernetes-using-helm/8771/27?u=braden

**Comment by antoviaque** [comment]
@bradenmacdonald I relayed your conclusion to the group during the meeting, the name `openedx-k8s-harmony` worked for everyone - we're good to go for the name change! :+1:

**Comment by antoviaque** [comment]
@bradenmacdonald Btw will you take care of opening the [tcril-engineering ticket](https://github.com/openedx/tcril-engineering/issues/new/choose) to get the repo renamed? Unless you already have the rights to do that, I don't seem to have them on my side.

**Comment by bradenmacdonald** [comment]
@antoviaque Done, requested via https://github.com/openedx/tcril-engineering/issues/661

**Comment by brian-smith-tcril** [comment]
Rename complete! https://github.com/openedx/tcril-engineering/issues/661#issuecomment-1424241109

**Comment by antoviaque** [comment]
@brian-smith-tcril @bradenmacdonald Great! Thank you :+1:
