### ISSUE TITLE
Karpenter?

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/openedx-k8s-harmony#7]
https://github.com/lpm0073/cookiecutter-openedx-devops uses [Karpenter](https://karpenter.sh/) to optimize the scheduling of k8s nodes at the cloud provider (e.g. AWS EC2 spot instances) to reduce costs of the cluster.

Is that in scope for this project for now, or do we want to stick to things that are provisioned within the cluster itself?

**Comment by jfavellar90** [comment]
As @lpm0073 mentioned in the meeting, adding [Karpenter](https://karpenter.sh/) requires the creation of a few entities in the cloud provider (AWS) to allow the cluster to interact with different cloud services via roles. Additionally, this service is only supported for AWS for now. The same applies to [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) tool, however, this one offers support for more cloud providers.

**Comment by lpm0073** [comment]
the Karpenter installation is segregated into a separate Terraform module in the Cookiecutter, see [Terraform/Karpenter](https://github.com/lpm0073/cookiecutter-openedx-devops/tree/main/%7B%7Bcookiecutter.github_repo_name%7D%7D/terraform/stacks/modules/kubernetes_karpenter).

You can probably copy-paste it nearly verbatim.

**Comment by bradenmacdonald** [comment]
Status: I would consider this a low priority issue for now because it mostly takes place outside of the helm chart.

I propose that the scope of this issue be: to test Lawrence's Karpenter integration and document how it can be used with this chart, for those who want to use it.

**Comment by antoviaque** [comment]
Note from the meeting - this work will be dependent on the work from @lpm0073 in https://github.com/openedx/tutor-contrib-multi/issues/3

**Comment by felipemontoya** [comment]
@lpm0073 we are looking at delegating this to someone else, would you agree?

**Comment by lpm0073** [comment]
@felipemontoya i'll follow up with via DM. i wasn't aware of anything pending nor ongoing w Karpenter. it's been nearly two months since i pushed my code. since then i haven't followed any ongoing dialogue in this project.

**Comment by felipemontoya** [comment]
For this cycle of review @jfavellar90 was on vacations so he will pick it up once he comes back
