### ISSUE TITLE
Discussion: Terraform scripts for setting up clusters

### ISSUE THREAD

**Issue by gabor-boros** [openedx/openedx-k8s-harmony#78]
Harmony is meant to provide the building blocks for anyone in the community to set up Open edX instances on scale. It provides the Helm chart for installing the necessary resources in the expected Kubernetes cluster, and a Tutor plugin to configure the instances in a way that is capable of handling users at scale. However, it doesn't provide the most important blocks for a production-ready setup: it does not provide any way to help with the Kubernetes and infrastructure cluster setup.

Harmony should, at least, provide Terraform modules to help to set up the necessary infrastructure. The current examples in the repository are not even close to a production-ready setup.

This issue is for initiating a discussion in the community, involving the service providers as well.

cc: @bradenmacdonald @cefboud @felipemontoya @MoisesGSalas @jfavellar90 @cmltaWt0

**Comment by bradenmacdonald** [comment]
As long as the Terraform modules are optional and clearly separate from the Helm charts, I think it's a good idea and will help people get started with k8s using best practices.

**Comment by gabor-boros** [comment]
Gentle reminder on this: @felipemontoya @MoisesGSalas @jfavellar90 @cmltaWt0

**Comment by felipemontoya** [comment]
I agree with Braden. As long as they are optional and clearly separated from the charts then we should not have any blocker for this.

**Comment by gabor-boros** [comment]
We have reached the end of this conversation with the outcome to upstream independent (but not provider independent) modules to Harmony. Closing this discussion.
