### ISSUE TITLE
Announce formal review period of the proposal

### ISSUE THREAD

**Issue by antoviaque** [openedx/openedx-k8s-harmony#8]
We have discussed doing a formal review of the proposal at https://github.com/openedx/open-edx-proposals/pull/372 until the next meeting on January 10th, to both give ourselves time to do the technical validation work captured in the issues on the current repo, and allow the rest of the community to join in the review, seeing that it is becoming more serious and defined now.

The review period should thus be until January 9th to allow us to debrief it during the next meeting - and in the announcement it's also worth asking people to review & comment before the end of this month, to keep some time to resolve discussions. The announcement category of discourse can be used to ensure we maximize the awareness of this within the community.

**Comment by antoviaque** [comment]
Note from the meeting: we seem all good to merge the ADR, but @felipemontoya would like to get formal approvals as :+1: on the PR from other core contributors before merging, which he has requested there from @bradenmacdonald @regisb @gabor-boros @jfavellar90 and @arbrandes

**Comment by felipemontoya** [comment]
The ADR was finally merged with status "provisional".

https://github.com/openedx/open-edx-proposals/pull/372
