### ISSUE TITLE
Restore missing access rights post-migration

### ISSUE THREAD

**Issue by antoviaque** [openedx/openedx-k8s-harmony#9]
See https://github.com/openedx/tcril-engineering/issues/577#issuecomment-1349610839

If I forgot anyone in my reply there, please shout!

**Comment by antoviaque** [comment]
@lpm0073 @MoisesGSalas @bradenmacdonald @keithgg @mtyaka @regisb @gabor-boros @jfavellar90 @sambapete @kmccormick (and anyone else I might be forgetting) We have lost access to the current repository in the transfer to the openedx org, as it requires core contributor status & specific access to the repo, like for the rest of the Open edX repos. This makes sense, and that could be a good occasion for a few more of us to become core contributors, as part of the work on this. Anyone interested? :)

See https://github.com/openedx/tcril-engineering/issues/577

> After discussing with the tCRIL team we've come to the conclusion that contributors (OpenCraft + outside collaborators) to openedx/tutor-contrib-multi should [follow the OEP-54 instructions](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html#adding-new-core-contributors) for adding new CCs or expanding the rights of existing CCs. [Here](https://discuss.openedx.org/t/core-contributor-nomination-maria-grimaldi/6548) is an example for nominating a new CC and [here](https://discuss.openedx.org/t/coding-cc-rights-expansion-piotr-surowiec/6958) is an example for expanding rights of an existing one.

So we'll probably need to differentiate between people who need to become core contributors for this, from those who are already core contributors and will only need new rights to access it. When replying here, please mention which case applies to you. :) 

To avoid spamming the official forum, we can probably group the right extensions together, and have dedicated nomination threads for each of the proposed new core contributors? (@sarina what do you think?)

**Comment by antoviaque** [comment]
@felipemontoya I forgot to ping you for this ^

**Comment by regisb** [comment]
Note that we don't need everyone to be a core contributor to participate in this project. Anyone (not just core contributors) can open PRs, just like for any other openedx repo. As far as I'm concerned I don't need core commit rights to this repo, I'll be just as happy if my PRs are reviewed.

**Comment by sarina** [comment]
> To avoid spamming the official forum, we can probably group the right extensions together, and have dedicated nomination threads for each of the proposed new core contributors? (@sarina what do you think?)

I'm not exactly sure what you'd like me to comment on. New CCs and rights expansions for existing CCs require separate forum threads, I am pretty sure OEP-54 states this.

**Comment by keithgg** [comment]
@antoviaque I agree with @regisb's sentiment. As long as that's the case, I'm happy to remain a non-CC for now :slightly_smiling_face:

**Comment by bradenmacdonald** [comment]
I agree that not everyone needs to be a CC to collaborate on this project. Let's just propose the rights expansion for those who are already CCs, and everyone else who wants to contribute can just open PRs. If they want to become CCs in the future, then their work here will only boost their eligibility :)

I also agree that there should just be one combined thread for this sort of expansion (adding a new repo); doing it separately is getting to sound like an overly bueaurocratic process. This won't be the last time that we're adding a new repo that several existing CCs want to collaborate on, and we should make that process simple. I also don't think it's healthy if we posted it as separate threads and there is some kind of popularity contest angle to it - i.e. comparing which CCs got more likes/comments for the exact same request, which may or may not mean anything.

Perhaps we should amend OEP-54 to say "Expanding a CC’s responsibilities should follow the same process as establishing a new contributor, _although a single combined forum thread can be used in cases where it makes sense to propose granting the same rights/responsibilities to a group of people, such as when creating a new repository_." Or even better, "when a CC chooses to create a new repository, they can freely grant rights/responsibilities to other interested CCs who have already been granted the same rights/responsibilities on similar repositories, at their discretion."

**Comment by sarina** [comment]
> Perhaps we should amend OEP-54 to say "Expanding a CC’s responsibilities should follow the same process as establishing a new contributor, although a single combined forum thread can be used in cases where it makes sense to propose granting the same rights/responsibilities to a group of people, such as when creating a new repository." Or even better, "when a CC chooses to create a new repository, they can freely grant rights/responsibilities to other interested CCs who have already been granted the same rights/responsibilities on similar repositories, at their discretion."

As long as it's clear that it's a facet of responsibility, not a new role. For example, if you had a group of three coding Core Contributors and they all wanted to become Product Manager Core Contributors, they would definitely need a separate thread to discuss their individual experiences backing up the new role.

**Comment by sarina** [comment]
but yeah "For new repo X, I nominate John, Julie, and Sally (already all coding CCs) to be CCs on this repo" makes sense to me.

**Comment by antoviaque** [comment]
Sounds good to me! I just wanted to make sure everyone who wanted to keep the rights on the repo could get an opportunity to do so, as I think we all want this to be a group effort on which we have shared ownership. 

Do we have anyone who would like to become a core contributor for this btw? @lpm0073 I think you were looking into it for documentation also already no?

Btw, on my side I don't necessarily need write access to the repo, but the ability to assign and edit tickets would be important, to allow me to keep tending the tickets, as I can't do anything with them anymore. @sarina I think there is now a bot that allows this, right? Do I need to do anything specific to benefit from this on this repo?

And +1 for the grouped thread for a single facet of responsibility - @sarina would we need to make an amendment in OEP-54 as suggested by @bradenmacdonald for this?

**Comment by sarina** [comment]
> Btw, on my side I don't necessarily need write access to the repo, but the ability to assign and edit tickets would be important, to allow me to keep tending the tickets, as I can't do anything with them anymore. @sarina I think there is now a bot that allows this, right? Do I need to do anything specific to benefit from this on this repo?

We don't have the bot in all repos. We can put the bots in this one if you wish (they grant ability to add/remove labels, and for an individual to assign themselves). There is the possibility of granting triage access to a limited # of people; I was separately planning to reach out to you about this but I've been slammed.

> And +1 for the grouped thread for a single facet of responsibility - @sarina would we need to make an amendment in OEP-54 as suggested by @bradenmacdonald for this?

Probably - that makes sense. I think it should be stated though that each individual would need some supporting evidence so people can still evaluate per-person.

**Comment by antoviaque** [comment]
@sarina 

> We don't have the bot in all repos. We can put the bots in this one if you wish (they grant ability to add/remove labels, and for an individual to assign themselves). There is the possibility of granting triage access to a limited # of people; I was separately planning to reach out to you about this but I've been slammed.

OK, I see - yes having the bots enabling this type of access on this repo would be great! Let me know if you want me to create a ticket for it somewhere, like it tcril-engineering?

> Probably - that makes sense. I think it should be stated though that each individual would need some supporting evidence so people can still evaluate per-person.

Sound good :+1: We currently don't have anyone to add this way I think, but @bradenmacdonald would you like to put your suggested change in a PR for review, this way it would be ready when/if we will need it?

**Comment by sarina** [comment]
>  Let me know if you want me to create a ticket for it somewhere, like it tcril-engineering?

Yes, a [tcril engineering access request](https://github.com/openedx/tcril-engineering/issues/new/choose) would be best. Could you please indicate all repos where it would be useful to you to have triage access?

**Comment by bradenmacdonald** [comment]
> but @bradenmacdonald would you like to put your suggested change in a PR for review, this way it would be ready when/if we will need it?

Sure I can do that next week.

**Comment by antoviaque** [comment]
@sarina 

> Yes, a [tcril engineering access request](https://github.com/openedx/tcril-engineering/issues/new/choose) would be best. Could you please indicate all repos where it would be useful to you to have triage access?

Done in https://github.com/openedx/tcril-engineering/issues/623#issuecomment-1406685013 -- let me know if you prefer a different ticket for this.

**Comment by felipemontoya** [comment]
I tried closing the issue #8 and noticed that I don't have that permission. Am I in the tutor-contrib-multi group?

According to https://github.com/openedx/tcril-engineering/issues/577 I should be.

**Comment by sarina** [comment]
@felipemontoya can you see https://github.com/orgs/openedx/people ? (it's one of the tabs on https://github.com/openedx for me, the "People" tab). If you can see this, you can look yourself up and see your teams & repo access.

**Comment by sarina** [comment]
@felipemontoya I don't see a tutor-contrib-multi group: https://github.com/orgs/openedx/teams?query=tutor

@kdmccormick I'm not sure what's going on with the tutor access, could you help out here?

**Comment by kdmccormick** [comment]
Sorry, I'm out of the loop on all this, I'm not sure what's going on.

**Comment by felipemontoya** [comment]
Thanks @sarina, now I can find myself and I'm definitely not in the group. But as as you mention I cant find any group for `tutor-contrib-multi`.

@Carlos-Muniz, mentioned [here](https://github.com/openedx/tcril-engineering/issues/577#issuecomment-1349595093) that as part of the migration from the open-craft repo there was a new openedx group that contained a list of people from the list that used to have write access.

We are also in the process of renaming this repo to ["openedx-k8s-harmony"](https://github.com/openedx/tutor-contrib-multi/issues/5#issuecomment-1421171587) but I can't find it under that name either.

**Comment by felipemontoya** [comment]
Yeeeiii, now the name is changed. Could we have the group created under the new name?
Should I open a tcril engineering ticket for that?

**Comment by bradenmacdonald** [comment]
I think you should, yeah. Thanks @felipemontoya !
